In [ ]:
import numpy as np
import pandas as pd

In [71]:
patients = pd.read_csv("patients.csv")

In [73]:
patients

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [75]:
patients.shape

(503, 14)

In [77]:
treatments = pd.read_csv('treatments.csv')
treatments.shape

(280, 7)

In [79]:
treatments_cut = pd.read_csv('treatments_cut.csv')
treatments_cut.shape

(70, 7)

In [81]:
adverse_reactions = pd.read_csv('adverse_reactions.csv')
adverse_reactions.shape

(34, 3)

Write a summary of your data

This is a data of 500 patients of which 350 patients participated in a clinical trial. None of them were using Novodra (a popular injectable insulin) or
Auralin (an oral insulin being researched) as a primary source of their insulin. All were experiencing elevated Hba1c level.

All 350 patients were treated with Novodra to establish a baseline Hba1c level or insulin dose. After 4 weeks which is not enough time to observe the change in Hba1c level that can be attributed by the switch to Novodra or Auralin.

1. 175 patients were switched to Auralin for 24 weeks
2. 175 patients were switched to Novodra for 24 weeks

Data for patient experiencing adverse effects is also recorded.

In [10]:
import numpy as np
import pandas as pd

In [11]:
with pd.ExcelWriter("clinical_trials.xlsx") as writer:
    patients.to_excel(writer,sheet_name = "patients",index=False)
    treatments.to_excel(writer,sheet_name= "treatments",index=False)
    treatments_cut.to_excel(writer,sheet_name= "treatments_cut",index=False)
    adverse_reactions.to_excel(writer,sheet_name= "adverse_reactions",index=False)

# Column Description
# Patients
1. Patient_id = Patient_id is the unique identifier for each patient in the master patient index (i.e. patient database) of the pharmaceutical company that is producing Auralin
2. The assigned_sex of each patient at birth (Male or Female)
3. given_name = the given name (i.e. first name) of each patient
4. surname = the surname (i.e. last name) of each patient
5. address = the main address for each patient
6. city = the city corresponding to the main address for each patient
7. state = the state corresponding to the main address for each patient
8. zip_code = the zip code corresponding to the main address for each patient
9. country = the country corresponding to the main address for each patient (All United States for this clinical trial)
10. contact = the phone number and email id for each patient
11. birthdate = the birthdate of each patient (mm/dd/yyyy). The inclusion criteria is age >= 18. There is no maximum age because diatebetes is a growing problem among elderly population
12. Weight = the weight of each patient in pounds (lbs).
13. Height = the height of each patient in inches.
14. bmi = the bmi index is body-mass index calculated by simply using a person's height and weight. The formula is kg/m2, where kg is the person's weight in kilogram and m2 is a person's height in metered square. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= bmi >= 38.

# Column description of treatments and treatments_cut
1. given_name = the given name of the patient in the master patient index who participated in the clinical trial
2. surname = the given name of the patient in the master patient index who participated in the clinical trial
3. Auralin = the baseline median of insulin dose from the week prior to switching to Auralin (the number before the dash) and the baseline insulin dose at the end of the treatment over the 24 weeks of treatment. Both are measured in units(u), which is international unit of measurement and standard measurement for insulin.
4. Novodra - Same as Auralin except for the patient who continued with Novodra.
5. hba1c_start - The patient's hba1c level at the beginning of the first week of the treatment. hba1c stands for hemoglobin a1c level. The hba1c test measures what the average blood sugar level has been over the last 3 or 4 months. It is a powerful way to get a overall sense of how blood sugar has been controlled. Everyone with diabetes should have this test 3 or 4 times in a year. Measured in %.
6. hba1c_end - The patients's blood sugar level at the end of the treatment.
7. hba1c_change - The change in patient's hba1c level from the start of the treatment to the end. For Auralin to be deemed effective, it must be non-inferior to Novodra, the current insulin standard. This non-inferiority is statistically defined as the upper bound of the 95% of the confidence interval being less than 0.4% for the difference between the mean changes of hba1c level for Auralin and Novodra (i.e. Novodra minus Auralin).

# Dirty Data (Data with quality issues)

- Patients
1. Patient ID has mis-spelled name Dsvid instead of David - 'accuracy'
2. State column sometimes contain full name and sometimes abbreviation - 'consistency'
3. Zip code column has entries with 4 digit - 'validity'
4. Data missing for 12 patients in Address, city, state, zipcode, country, contact - 'completeness'
5. Incorrect datatype in assigned_sex, zip_code and birthdate - 'accuracy'
6. Duplicated entry by the name of John Doe - 'accuracy'
7. One patient has weight 48.80 pounds and one patient has height 27 inches 'accuracy'
- treatments and treatments_cut
1. given name and surname are all in lower case - 'consistency'
2. u should be removed from Auralin column and same as Novodra - 'validity'
3. '-' in Auralin and Novodra treated as Nan 'validity'
4. Missing values in hba1c change column 'completeness'
5. hba1c column has 9 missing values 'completeness'
6. Duplicated entry by the name of Joseph day 'accuracy'
7. In 'hba1c_change' 9 instead of 4 'accuracy'
- Adverse_reactions
1. given name and surname are in lower case 'consistency'

# Messy Data (Data with tidiness issues)

- Patients
1. Contact column contains both phone and email id
- treatments and treatments_cut
1. Auralin column should be splited into 2 columns, one with start value and the other with end value and same as Novodra
2. Merge both tables
- Adverse_reactions
1. This table should not exist independently

# Automatic Assessment
1. Head and tail
2. Sample
3. Info
4. isnull()
5. duplicated()
6. describe()

In [83]:
patients.sample()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
183,184,male,Suhaim,Rahal,2270 Bel Meadow Drive,Fontana,California,92335.0,United States,909-355-9418SuhaimAbdelRahal@fleckens.hu,2/8/1944,207.7,71,29.0

In [85]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [87]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [89]:
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [91]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [93]:
patients.sample()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2

In [95]:
patients.duplicated().sum()

0

In [97]:
patients['patient_id'].duplicated().sum()

0

In [99]:
patients.duplicated(subset=['given_name','surname']).sum()

5

In [101]:
patients[patients.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [103]:
treatments.duplicated().sum()

1

In [105]:
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [107]:
treatments_cut[treatments_cut.duplicated()]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [109]:
adverse_reactions.duplicated().sum()

0

In [111]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [113]:
patients[patients['weight']==48.800000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [115]:
patients[patients['height']==27]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [117]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [119]:
treatments.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99

In [121]:
treatments_cut.describe()

       hba1c_start  hba1c_end  hba1c_change
count    70.000000  70.000000     42.000000
mean      7.838000   7.443143      0.518810
std       0.423007   0.418706      0.270719
min       7.510000   7.020000      0.280000
25%       7.640000   7.232500      0.340000
50%       7.730000   7.345000      0.370000
75%       7.860000   7.467500      0.907500
max       9.910000   9.460000      0.970000

# Steps involved in Data cleaning
1. Define
2. Code
3. Test

# Always make sure that you make a copy of pandas dataframe before cleaning process starts

In [141]:
patients_df = patients.copy()
treatments_df = treatments.copy()
treatments_cut_df = treatments_cut.copy()
adverse_reactions_df = adverse_reactions.copy()

In [143]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [42]:
#Define
# Replace all missing values of patients_df with 'No data'
# Replace missing values of hba1c_change by subtracting hba1c_end from hba1c_start
# contact column will be separated in 2 columns phone and email_id by Regex method

In [145]:
# Code
patients_df.fillna('No Data', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_10552\1513171298.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No Data' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patients_df.fillna('No Data', inplace=True)

In [147]:
# Test
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

In [149]:
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [151]:
treatments_df['hba1c_change']=treatments_df['hba1c_start']-treatments_df['hba1c_end']
treatments_cut_df['hba1c_change']=treatments_cut_df['hba1c_start']-treatments_cut_df['hba1c_end']

In [153]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [155]:
treatments_cut_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [157]:
patients_df['email_id'] = patients_df['contact'].str.extract(
    r'([A-Za-z]+[A-Za-z0-9._%+-]*@[A-Za-z0-9.-]+\.[A-Za-z]{2,})'
)

patients_df['phone'] = patients_df['contact'].str.replace(
    r'([A-Za-z]+[A-Za-z0-9._%+-]*@[A-Za-z0-9.-]+\.[A-Za-z]{2,})',
    '',
    regex=True
)

In [159]:
patients_df.drop('email',axis=1,inplace=True)

KeyError: "['email'] not found in axis"

In [ ]:
patients_df

In [208]:
patients_df.drop('contact',axis=1,inplace=True)

In [55]:
patients_df

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email_id
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,951-719-9170,ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,+1 (217) 569-3204,PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,2/19/1980,177.8,71,24.8,402-363-6804,JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,+1 (732) 636-8246,PhanBaLiem@jourrapide.com
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,2/18/1928,192.3,27,26.1,334-515-7487,TimNeudorf@cuvox.de
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,4/10/1959,181.1,72,24.6,207-477-0579,MustafaLindstrom@jourrapide.com
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,3/26/1948,239.6,70,34.4,928-284-4492,RumanBisliev@gustr.com
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,1/13/1971,171.2,67,26.8,816-223-6007,JinkedeKeizer@teleworm.us
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,2/13/1952,176.9,67,27.7,1 360 443 2060,ChidaluOnyekaozulu@jourrapide.com
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,5/3/1954,138.2,71,19.3,402-848-4923,PatrickGersten@rhyta.com

In [162]:
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,0.32
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [164]:
treatments_df = pd.concat([treatments_df,treatments_cut_df])

In [166]:
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [168]:
treatments_df=treatments_df.melt(id_vars=['given_name','surname','hba1c_start','hba1c_end','hba1c_change'],var_name='type',value_name='dosage_range')

In [170]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
1,elliot,richardson,7.56,7.09,0.47,auralin,-
2,yukitaka,takenaka,7.68,7.25,0.43,auralin,-
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,alissa,montez,7.78,7.46,0.32,auralin,-
...,...,...,...,...,...,...,...
695,rovzan,kishiev,7.75,7.41,0.34,novodra,-
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
697,bernd,schneider,7.74,7.44,0.30,novodra,-
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u
699,armina,sauvé,7.86,7.40,0.46,novodra,-

In [172]:
treatments_df=treatments_df[treatments_df['dosage_range'] != '-']

In [174]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u

In [176]:
treatments_df['dosage_start']=treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end']=treatments_df['dosage_range'].str.split('-').str.get(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_10552\3603672503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start']=treatments_df['dosage_range'].str.split('-').str.get(0)
C:\Users\HP\AppData\Local\Temp\ipykernel_10552\3603672503.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end']=treatments_df['dosage_range'].str.split('-').str.get(1)

In [178]:
treatments_df.drop('dosage_range',axis=1,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_10552\1798141223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df.drop('dosage_range',axis=1,inplace=True)

In [180]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u,36u
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u,44u

In [182]:
treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u','')
treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u','')

C:\Users\HP\AppData\Local\Temp\ipykernel_10552\3184756727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u','')
C:\Users\HP\AppData\Local\Temp\ipykernel_10552\3184756727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u','')

In [184]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55,51
690,maret,sultygov,7.67,7.30,0.37,novodra,26,23
694,lixue,hsueh,9.21,8.80,0.41,novodra,22,23
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26
698,berta,napolitani,7.68,7.21,0.47,novodra,42,44

In [186]:
treatments_df=treatments_df.merge(adverse_reactions_df,how='left',on=['given_name','surname'])

In [188]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [70]:
# treatments and treatments_cut
# Adverse_reactions
1. given name and surname are in lower case 'consistency'

SyntaxError: invalid syntax (561023594.py, line 1)

In [190]:
# Issue 1 - Patient ID has mis-spelled name Dsvid instead of David - 'accuracy'
patients_df.loc[patients_df['patient_id']==9,'given_name'] = 'David'
patients_df.loc[patients_df['patient_id']==9,'given_name']

8    David
Name: given_name, dtype: object

In [192]:
# Issue 2 - State column sometimes contain full name and sometimes abbreviation - 'consistency'
patients_df.state.value_counts()

state
California    36
TX            32
New York      25
CA            24
NY            22
MA            22
PA            18
GA            15
Illinois      14
OH            14
Florida       13
MI            13
OK            13
LA            13
NJ            12
No Data       12
VA            11
MS            10
WI            10
IL            10
IN             9
MN             9
FL             9
TN             9
AL             9
NC             8
KY             8
WA             8
MO             7
ID             6
KS             6
NV             6
SC             5
IA             5
CT             5
ME             4
ND             4
Nebraska       4
RI             4
AR             4
CO             4
AZ             4
MD             3
DE             3
WV             3
OR             3
SD             3
MT             2
VT             2
DC             2
NE             2
AK             1
WY             1
NH             1
NM             1
Name: count, dtype: int64

In [194]:
state_abbreviations = {
    'California': 'CA',
    'Texas': 'TX',
    'New York': 'NY',
    'Massachusetts': 'MA',
    'Pennsylvania': 'PA',
    'Georgia': 'GA',
    'Illinois': 'IL',
    'Ohio': 'OH',
    'Florida': 'FL',
    'Michigan': 'MI',
    'Oklahoma': 'OK',
    'Louisiana': 'LA',
    'New Jersey': 'NJ',
    'Virginia': 'VA',
    'Mississippi': 'MS',
    'Wisconsin': 'WI',
    'Indiana': 'IN',
    'Minnesota': 'MN',
    'Tennessee': 'TN',
    'Alabama': 'AL',
    'North Carolina': 'NC',
    'Kentucky': 'KY',
    'Washington': 'WA',
    'Missouri': 'MO',
    'Idaho': 'ID',
    'Kansas': 'KS',
    'Nevada': 'NV',
    'South Carolina': 'SC',
    'Iowa': 'IA',
    'Connecticut': 'CT',
    'Maine': 'ME',
    'North Dakota': 'ND',
    'Nebraska': 'NE',
    'Rhode Island': 'RI',
    'Arkansas': 'AR',
    'Colorado': 'CO',
    'Arizona': 'AZ',
    'Maryland': 'MD',
    'Delaware': 'DE',
    'West Virginia': 'WV',
    'Oregon': 'OR',
    'South Dakota': 'SD',
    'Montana': 'MT',
    'Vermont': 'VT',
    'District of Columbia': 'DC',
    'Alaska': 'AK',
    'Wyoming': 'WY',
    'New Hampshire': 'NH',
    'New Mexico': 'NM',
    'No data': 'Unknown'
}

In [196]:
# Apply changes to DataFrame
patients_df['state']=patients_df['state'].apply(lambda x: state_abbreviations.get(x,x))

print(patients_df['state'].value_counts())

state
CA         60
NY         47
TX         32
IL         24
FL         22
MA         22
PA         18
GA         15
OH         14
MI         13
OK         13
LA         13
NJ         12
No Data    12
VA         11
WI         10
MS         10
IN          9
MN          9
TN          9
AL          9
WA          8
KY          8
NC          8
MO          7
NV          6
KS          6
ID          6
NE          6
SC          5
CT          5
IA          5
CO          4
ND          4
RI          4
ME          4
AR          4
AZ          4
SD          3
MD          3
WV          3
OR          3
DE          3
VT          2
MT          2
DC          2
WY          1
AK          1
NH          1
NM          1
Name: count, dtype: int64

In [ ]:
# Issue - 3. Zip code column has entries with 4 digit - 'validity'

In [198]:
patients_df['zip_code'].apply(str).str.len().value_counts()

zip_code
7    454
6     49
Name: count, dtype: int64

In [200]:
patients_df.zip_code.sample(5)

470    32064.0
200     8110.0
125    74119.0
168    94306.0
403     2908.0
Name: zip_code, dtype: object

In [202]:
# Zip_code is in string but decimal format. Need to remove decimal part and fill zeros upfrom to make it in 5 digit format.
# Function to make zip_code in 5 digit format
def clean_zip_code(zip_code):
    if zip_code == 'No Data':
        return 'NA'
    zip_code = int(float(zip_code)) # remove decimal part
    return str(zip_code).zfill(5)   # convert to string and pad with zero

patients_df['zip_code'].apply(clean_zip_code).str.len().value_counts()

zip_code
5    491
2     12
Name: count, dtype: int64

In [204]:
patients_df['zip_code'] = patients_df['zip_code'].apply(clean_zip_code)

In [210]:
patients_df

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,CA,92390,United States,7/10/1976,121.7,66,19.6,ZoeWellish@superrito.com,951-719-9170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,IL,61812,United States,4/3/1967,118.8,66,19.2,PamelaSHill@cuvox.de,+1 (217) 569-3204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,NE,68467,United States,2/19/1980,177.8,71,24.8,JaeMDebord@gustr.com,402-363-6804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,07095,United States,7/26/1951,220.9,70,31.7,PhanBaLiem@jourrapide.com,+1 (732) 636-8246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303,United States,2/18/1928,192.3,27,26.1,TimNeudorf@cuvox.de,334-515-7487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,03852,United States,4/10/1959,181.1,72,24.6,MustafaLindstrom@jourrapide.com,207-477-0579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341,United States,3/26/1948,239.6,70,34.4,RumanBisliev@gustr.com,928-284-4492
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110,United States,1/13/1971,171.2,67,26.8,JinkedeKeizer@teleworm.us,816-223-6007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109,United States,2/13/1952,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,1 360 443 2060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,NE,68324,United States,5/3/1954,138.2,71,19.3,PatrickGersten@rhyta.com,402-848-4923

In [212]:
patients_df

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,CA,92390,United States,7/10/1976,121.7,66,19.6,ZoeWellish@superrito.com,951-719-9170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,IL,61812,United States,4/3/1967,118.8,66,19.2,PamelaSHill@cuvox.de,+1 (217) 569-3204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,NE,68467,United States,2/19/1980,177.8,71,24.8,JaeMDebord@gustr.com,402-363-6804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,07095,United States,7/26/1951,220.9,70,31.7,PhanBaLiem@jourrapide.com,+1 (732) 636-8246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303,United States,2/18/1928,192.3,27,26.1,TimNeudorf@cuvox.de,334-515-7487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,03852,United States,4/10/1959,181.1,72,24.6,MustafaLindstrom@jourrapide.com,207-477-0579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341,United States,3/26/1948,239.6,70,34.4,RumanBisliev@gustr.com,928-284-4492
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110,United States,1/13/1971,171.2,67,26.8,JinkedeKeizer@teleworm.us,816-223-6007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109,United States,2/13/1952,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,1 360 443 2060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,NE,68324,United States,5/3/1954,138.2,71,19.3,PatrickGersten@rhyta.com,402-848-4923

In [214]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [216]:
adverse_reactions_df

     given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miłosław  wiśniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lončar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

In [ ]:
# Issue - 4. Data missing for 12 patients in Address, city, state, zipcode, country, contact - 'completeness'

In [220]:
patients_df[patients_df.isnull().any(axis=1)]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
209,210,female,Lalita,Eldarkhanov,No Data,No Data,No Data,NA,No Data,8/14/1950,143.4,62,26.2,NaN,No Data
219,220,male,Mỹ,Quynh,No Data,No Data,No Data,NA,No Data,4/9/1978,237.8,69,35.1,NaN,No Data
230,231,female,Elisabeth,Knudsen,No Data,No Data,No Data,NA,No Data,9/23/1976,165.9,63,29.4,NaN,No Data
234,235,female,Martina,Tománková,No Data,No Data,No Data,NA,No Data,4/7/1936,199.5,65,33.2,NaN,No Data
242,243,male,John,O'Brian,No Data,No Data,No Data,NA,No Data,2/25/1957,205.3,74,26.4,NaN,No Data
249,250,male,Benjamin,Mehler,No Data,No Data,No Data,NA,No Data,10/30/1951,146.5,69,21.6,NaN,No Data
257,258,male,Jin,Kung,No Data,No Data,No Data,NA,No Data,5/17/1995,231.7,69,34.2,NaN,No Data
264,265,female,Wafiyyah,Asfour,No Data,No Data,No Data,NA,No Data,11/3/1989,158.6,63,28.1,NaN,No Data
269,270,female,Flavia,Fiorentino,No Data,No Data,No Data,NA,No Data,10/9/1937,175.2,61,33.1,NaN,No Data
278,279,female,Generosa,Cabán,No Data,No Data,No Data,NA,No Data,12/16/1962,124.3,69,18.4,NaN,No Data
286,287,male,Lewis,Webb,No Data,No Data,No Data,NA,No Data,4/1/1979,155.3,68,23.6,NaN,No Data
296,297,female,Chỉ,Lâm,No Data,No Data,No Data,NA,No Data,5/14/1990,181.1,63,32.1,NaN,No Data

In [222]:
patients_df[['address','city','state','zip_code','country']] = patients_df[['address','city','state','zip_code','country']].fillna('Unknown',axis=1)

In [226]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email_id      491 non-null    object
 14  phone         503 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 59.1+ KB

In [234]:
patients_df['email_id'] = patients_df['email_id'].fillna('Unknown')

In [236]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email_id      503 non-null    object
 14  phone         503 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 59.1+ KB

In [ ]:
# Issue 5. Incorrect datatype in assigned_sex, zip_code and birthdate - 'accuracy'

In [238]:
patients_df['assigned_sex'] = patients_df['assigned_sex'].astype('category')
patients_df['zip_code'] = patients_df['zip_code'].astype(str)
patients_df['birthdate'] = pd.to_datetime(patients_df['birthdate'],errors='coerce')

In [240]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    category
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    datetime64[ns]
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email_id      503 non-null    object
 14  phone         503 non-null    object
dtypes: category(1), datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 55.8+ KB

In [ ]:
# Issue 6: duplicate entries by the name of John Doe accuracy

In [244]:
patients_df[patients_df.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
229,230,male,John,Doe,123 Main Street,New York,NY,12345,United States,1975-01-01,180.0,72,24.4,johndoe@email.com,1234567890
237,238,male,John,Doe,123 Main Street,New York,NY,12345,United States,1975-01-01,180.0,72,24.4,johndoe@email.com,1234567890
244,245,male,John,Doe,123 Main Street,New York,NY,12345,United States,1975-01-01,180.0,72,24.4,johndoe@email.com,1234567890
251,252,male,John,Doe,123 Main Street,New York,NY,12345,United States,1975-01-01,180.0,72,24.4,johndoe@email.com,1234567890
277,278,male,John,Doe,123 Main Street,New York,NY,12345,United States,1975-01-01,180.0,72,24.4,johndoe@email.com,1234567890

In [246]:
patients_df.drop_duplicates(subset=['given_name','surname'],inplace=True)

In [250]:
patients_df.duplicated(subset=['given_name','surname'])

0      False
1      False
2      False
3      False
4      False
       ...
498    False
499    False
500    False
501    False
502    False
Length: 498, dtype: bool

In [ ]:
# Issue - 7. One patient has weight 48.80 pounds and one patient has height 27 inches 'accuracy'

In [254]:
patients_df[patients_df['weight'] == 48.80]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691,United States,1938-11-26,48.8,63,19.1,CamillaZaitseva@superrito.com,330-202-2145

In [256]:
patients_df[patients_df['height'] == 27]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email_id,phone
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303,United States,1928-02-18,192.3,27,26.1,TimNeudorf@cuvox.de,334-515-7487

In [ ]:
weight_lb = 48.8
weight_kg = 48.8*0.45359237 = 22.1353076
height_inches = 63
height_metre = 1.6002
bmi = 19.1
bmi = kg/m**2
kg = 19.1*2.56064004
weight_lbs = 107.824179

In [262]:
patients_df.loc[patients_df['weight'] == 48.80,'weight'] = 107.824179

In [264]:
patients_df.iloc[210]

patient_id                                211
assigned_sex                           female
given_name                            Camilla
surname                              Zaitseva
address                   4689 Briarhill Lane
city                                  Wooster
state                                      OH
zip_code                                44691
country                         United States
birthdate                 1938-11-26 00:00:00
weight                             107.824179
height                                     63
bmi                                      19.1
email_id        CamillaZaitseva@superrito.com
phone                            330-202-2145
Name: 210, dtype: object

In [274]:
patients_df.loc[patients_df['height'] == 27,'height'] = 71.97

C:\Users\HP\AppData\Local\Temp\ipykernel_10552\2495630814.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '71.97' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  patients_df.loc[patients_df['height'] == 27,'height'] = 71.97

In [276]:
patients_df.iloc[4]

patient_id                         5
assigned_sex                    male
given_name                       Tim
surname                      Neudorf
address         1428 Turkey Pen Lane
city                          Dothan
state                             AL
zip_code                       36303
country                United States
birthdate        1928-02-18 00:00:00
weight                         192.3
height                         71.97
bmi                             26.1
email_id         TimNeudorf@cuvox.de
phone                   334-515-7487
Name: 4, dtype: object

In [ ]:
# treatments and treatments_cut
# Issue 1. given name and surname are all in lower case - 'consistency'

In [282]:
treatments_df['given_name'] = treatments_df['given_name'].str.title()

In [284]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,Christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,Maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,Lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,Jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,Berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [ ]:
# Issue 3. '-' in Auralin and Novodra treated as Nan 'validity'

In [292]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,Christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,Maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,Lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,Jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,Berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [316]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,Christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,Maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,Lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,Jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,Berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [320]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        350 non-null    object
 1   surname           350 non-null    object
 2   hba1c_start       350 non-null    float64
 3   hba1c_end         350 non-null    float64
 4   hba1c_change      350 non-null    float64
 5   type              350 non-null    object
 6   dosage_start      350 non-null    object
 7   dosage_end        350 non-null    object
 8   adverse_reaction  35 non-null     object
dtypes: float64(3), object(6)
memory usage: 24.7+ KB

In [332]:
treatments_df.drop_duplicates(subset=['given_name','surname'],inplace=True)

In [336]:
treatments_df[treatments_df.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, hba1c_start, hba1c_end, hba1c_change, type, dosage_start, dosage_end, adverse_reaction]
Index: []

In [ ]:
# Issue - 7. In 'hba1c_change' 9 instead of 4 'accuracy'

In [352]:
treatments_df['hba1c_change_modified']=treatments_df['hba1c_start']-treatments_df['hba1c_end']

In [346]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 349 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        349 non-null    object
 1   surname           349 non-null    object
 2   hba1c_start       349 non-null    float64
 3   hba1c_end         349 non-null    float64
 4   hba1c_change      349 non-null    float64
 5   type              349 non-null    object
 6   dosage_start      349 non-null    object
 7   dosage_end        349 non-null    object
 8   adverse_reaction  34 non-null     object
dtypes: float64(3), object(6)
memory usage: 27.3+ KB

In [366]:
treatments_df.sort_values('hba1c_change_modified',ascending=False)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction,hba1c_change_modified
91,Kerman,dandonneau,7.82,7.28,0.54,auralin,41,50,NaN,0.54
217,Hideki,haraguchi,7.59,7.05,0.54,novodra,37,35,NaN,0.54
23,Kristoffer,martinsen,9.18,8.64,0.54,auralin,29,37,NaN,0.54
267,León,reynoso,7.59,7.06,0.53,novodra,38,40,NaN,0.53
131,Kate,wilkinson,7.72,7.20,0.52,auralin,36,39,NaN,0.52
...,...,...,...,...,...,...,...,...,...,...
100,Nicolas,ferreira,7.99,7.72,0.27,auralin,43,51,NaN,0.27
66,Nicoline,østergaard,7.84,7.57,0.27,auralin,24,32,NaN,0.27
119,Manouck,wubbels,7.66,7.40,0.26,auralin,55,62,throat irritation,0.26
210,Tosh,jensen,7.93,7.69,0.24,novodra,51,48,NaN,0.24
133,Albina,zetticci,7.93,7.73,0.20,auralin,45,51,NaN,0.20

In [370]:
treatments_df.drop('hba1c_change',inplace=True,axis=1)

In [372]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,type,dosage_start,dosage_end,adverse_reaction,hba1c_change_modified
0,Veronika,jindrová,7.63,7.20,auralin,41,48,NaN,0.43
1,Skye,gormanston,7.97,7.62,auralin,33,36,NaN,0.35
2,Sophia,haugen,7.65,7.27,auralin,37,42,NaN,0.38
3,Eddie,archer,7.89,7.55,auralin,31,38,NaN,0.34
4,Asia,woźniak,7.76,7.37,auralin,30,36,NaN,0.39
...,...,...,...,...,...,...,...,...,...
345,Christopher,woodward,7.51,7.06,novodra,55,51,nausea,0.45
346,Maret,sultygov,7.67,7.30,novodra,26,23,NaN,0.37
347,Lixue,hsueh,9.21,8.80,novodra,22,23,injection site discomfort,0.41
348,Jakob,jakobsen,7.96,7.51,novodra,28,26,hypoglycemia,0.45
349,Berta,napolitani,7.68,7.21,novodra,42,44,injection site discomfort,0.47

In [ ]:
# Adverse_reactions
# 1. given name and surname are in lower case 'consistency'

In [378]:
adverse_reactions_df = adverse_reactions_df['given_name'].str.title()

In [380]:
adverse_reactions_df = adverse_reactions_df['surname'].str.title()

KeyError: 'surname'

In [381]:
adverse_reactions_df

0           Berta
1            Lena
2          Joseph
3          Flavia
4         Manouck
5         Jasmine
6          Louise
7         Albinca
8             Noe
9           Sofia
10          Tegan
11           Abel
12      Abdul-Nur
13           Leon
14       Gabriele
15         Jia Li
16          Jakob
17    Christopher
18            Ole
19         Finley
20       Anenechi
21       Miłosław
22          Lixue
23          Merci
24           Kang
25         Elliot
26        Clinton
27         Idalia
28         Xiuxiu
29           Alex
30         Monika
31         Steven
32        Cecilie
33      Krisztina
Name: given_name, dtype: object

In [389]:
treatments_df['surname']=treatments_df['surname'].str.title()

In [393]:
treatments_df = treatments_df[['given_name','surname','hba1c_start','hba1c_end','type','dosage_start','dosage_end','hba1c_change_modified','adverse_reaction']]

In [395]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,type,dosage_start,dosage_end,hba1c_change_modified,adverse_reaction
0,Veronika,Jindrová,7.63,7.20,auralin,41,48,0.43,NaN
1,Skye,Gormanston,7.97,7.62,auralin,33,36,0.35,NaN
2,Sophia,Haugen,7.65,7.27,auralin,37,42,0.38,NaN
3,Eddie,Archer,7.89,7.55,auralin,31,38,0.34,NaN
4,Asia,Woźniak,7.76,7.37,auralin,30,36,0.39,NaN
...,...,...,...,...,...,...,...,...,...
345,Christopher,Woodward,7.51,7.06,novodra,55,51,0.45,nausea
346,Maret,Sultygov,7.67,7.30,novodra,26,23,0.37,NaN
347,Lixue,Hsueh,9.21,8.80,novodra,22,23,0.41,injection site discomfort
348,Jakob,Jakobsen,7.96,7.51,novodra,28,26,0.45,hypoglycemia
349,Berta,Napolitani,7.68,7.21,novodra,42,44,0.47,injection site discomfort

In [403]:
treatments_df['hba1c_change']=treatments_df['hba1c_change_modified'].rename()

In [409]:
treatments_df.drop('hba1c_change',inplace=True,axis=1)

In [423]:
with pd.ExcelWriter('clinical_trials_cleaned.xlsx') as writer:
    patients_df.to_excel(writer,sheet_name='patients_df',index=False)
    treatments_df.to_excel(writer,sheet_name='treatments_df',index=False)

In [421]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 349 entries, 0 to 349
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   given_name             349 non-null    object
 1   surname                349 non-null    object
 2   hba1c_start            349 non-null    float64
 3   hba1c_end              349 non-null    float64
 4   type                   349 non-null    object
 5   dosage_start           349 non-null    int32
 6   dosage_end             349 non-null    int32
 7   hba1c_change_modified  349 non-null    float64
 8   adverse_reaction       34 non-null     object
dtypes: float64(3), int32(2), object(4)
memory usage: 32.6+ KB

In [419]:
treatments_df['dosage_start'] = treatments_df['dosage_start'].astype(int)
treatments_df['dosage_end'] = treatments_df['dosage_end'].astype(int)

In [425]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 498 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    498 non-null    int64
 1   assigned_sex  498 non-null    category
 2   given_name    498 non-null    object
 3   surname       498 non-null    object
 4   address       498 non-null    object
 5   city          498 non-null    object
 6   state         498 non-null    object
 7   zip_code      498 non-null    object
 8   country       498 non-null    object
 9   birthdate     498 non-null    datetime64[ns]
 10  weight        498 non-null    float64
 11  height        498 non-null    float64
 12  bmi           498 non-null    float64
 13  email_id      498 non-null    object
 14  phone         498 non-null    object
dtypes: category(1), datetime64[ns](1), float64(3), int64(1), object(9)
memory usage: 59.0+ KB